import random
letters=['a','b','c','s','d','e','f','g','h','i','j','k','l',
         'm','n','o','p','q','r','s','t','u','v','w','x',
         'y','z','A','B','C','D','E','F','G','H','I','J','K','L',
         'M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
symbols=['!','@','#','$','%','^','&','*','(',')','_']
numbers=['0','1','2','3','4','5','6','7','8','9']
print("WELCOME TO THE PASSWORD GENERATOR!!!")
import random
letter=int(input("How many letetr would you like in your password?? \n"))
symbol=int(input("How many symbol would you like in your password?? \n"))
number=int(input("How many number would you like in your password??  \n"))
password_list=[]
for i in range(1,letter+1):
    char=random.choice(letters)
    password_list+=char
for i in range(1,symbol+1):
    char=random.choice(symbols)
    password_list+=char
for i in range(1,number+1):
    char=random.choice(numbers)
    password_list+=char
random.shuffle(password_list)
password=" "
for char in password_list:
    password+=char
print("password generated by the user is:",password)